[project]
name = "clip-service"
version = "0.1.0"
description = "Python-based CLIP service"
authors = [
    {name = "Camilla Thorsen", email = "camilla@thorsen.dev"}
]
license = {text = "UNLICENSED"}
requires-python = ">=3.11"
dependencies = [
  "torch (>=2.7.1,<3.0.0)",
  "transformers (>=4.52.4,<5.0.0)",
  "pillow (>=11.2.1,<12.0.0)",
  "fastapi (>=0.115.12,<0.116.0)",
  "uvicorn[standard] (>=0.34.3,<0.35.0)",
  "python-multipart"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
